
FROM python:3.12-slim
WORKDIR /app
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./auto_post_api /app
CMD  uvicorn scrap_py:app --proxy-headers --host 0.0.0.0  --port 9004

EXPOSE 9004
